In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("train_updated.csv", encoding="utf-8", usecols=range(2, 27))
train_data = df.replace(['NR'], [0.0]) 
# train_data is a complete dataset including all observations

In [3]:
pm2_5 = train_data[train_data['測項']=='PM2.5'].iloc[:,1:]
# pm2_5 is a subset of complete dataset: only contains PM2.5 observations

In [5]:
# rearranging train_data
tempxlist = []
tempylist = []
for i in range (15):
    tempx = pm2_5.iloc[:,i:i+9]
    tempx.columns = np.array(range(9))
    tempy = pm2_5.iloc[:,i+9]
    tempy.columns = ['1']
    tempxlist.append(tempx)
    tempylist.append(tempy)

In [6]:
xdata = pd.concat(tempxlist)
x = np.array(xdata, float)
x

array([[26., 39., 36., ..., 25., 20., 19.],
       [21., 23., 30., ..., 13., 13., 11.],
       [19., 25., 27., ..., 15.,  8.,  4.],
       ...,
       [31., 31., 36., ..., 39., 36., 24.],
       [21., 21., 19., ..., 11.,  0.,  7.],
       [ 1.,  7., 24., ..., 28., 17., 24.]])

In [7]:
x.shape

(3600, 9)

In [8]:
ydata = pd.concat(tempylist)
ydata.head()
y = np.array(ydata, float)
y

array([30., 22.,  9., ..., 23.,  7., 29.])

In [9]:
y.shape

(3600,)

In [10]:
x.shape[0]

3600

In [11]:
bdata = np.ones((x.shape[0],1))  # initial bias = 1

In [12]:
x = np.concatenate((bdata, x), axis=1)
x

array([[ 1., 26., 39., ..., 25., 20., 19.],
       [ 1., 21., 23., ..., 13., 13., 11.],
       [ 1., 19., 25., ..., 15.,  8.,  4.],
       ...,
       [ 1., 31., 31., ..., 39., 36., 24.],
       [ 1., 21., 21., ..., 11.,  0.,  7.],
       [ 1.,  1.,  7., ..., 28., 17., 24.]])

In [14]:
_l = len(x[0])
weights = np.zeros((_l))

In [24]:
learn_rate = 1
iteration = 10000
s_grad = np.zeros(_l)

In [26]:
for i in range (iteration):
    y_prime = np.dot(x, weights)
    loss = y - y_prime
    grad = np.dot(x.transpose(), loss)*(-2)
    s_grad += grad**2
    ada = np.sqrt(s_grad)
    weights = weights - learn_rate*grad/ada

In [23]:
weights

array([ 2.14416897e+00,  2.49247404e-04, -3.70737877e-02,  2.04450118e-01,
       -2.25701620e-01, -2.98680931e-02,  4.65538636e-01, -5.57069337e-01,
        2.57164804e-02,  1.07483375e+00])

In [27]:
# so the weights above should be the best b and ws
# now let's start predicting

testdata = pd.read_csv("test_X.csv")

In [28]:
testdata

        id_0    AMB_TEMP    15    14  14.1    13  13.1  13.2  13.3  13.4    12
0       id_0         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
1       id_0          CO  0.36  0.35  0.34  0.33  0.33  0.34  0.34  0.37  0.42
2       id_0        NMHC  0.11  0.09  0.09   0.1   0.1   0.1   0.1  0.11  0.12
3       id_0          NO   0.6   0.4   0.3   0.3   0.3   0.7   0.8   0.8   0.9
4       id_0         NO2   9.3   7.1   6.1   5.7   5.5   5.3   5.5   7.1   7.5
5       id_0         NOx   9.9   7.5   6.4   5.9   5.8     6   6.2   7.8   8.4
6       id_0          O3    36    44    45    44    44    44    43    40    38
7       id_0        PM10    51    51    31    40    34    51    42    36    30
8       id_0       PM2.5    27    13    24    29    41    30    29    27    28
9       id_0    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
10      id_0          RH    75    71    71    73    74    74    74    74    74
11      id_0         SO2   1.2   1.2   1.2   1.6   1.5   1.5   1.5   1.6   1.6
12      id_0         THC   1.9   1.8   1.8   1.9   1.9   1.9   1.9   1.9   1.9
13      id_0       WD_HR   116   114   112   109   111   104   107   108   104
14      id_0  WIND_DIREC   115   113   105   102   106   106   112   113   106
15      id_0  WIND_SPEED   2.6   2.2     2   1.9   2.4   2.4   2.5   2.8     2
16      id_0       WS_HR   2.1   2.4   2.2   1.9   2.3   2.3   2.5   2.5   2.3
17      id_1    AMB_TEMP    12    12    12    13    14    15    14    14    13
18      id_1         CH4   1.8   1.8   1.9   1.9   1.8   1.8   1.8   1.8   1.8
19      id_1          CO  0.46  0.58  0.64  0.63  0.58  0.52  0.52  0.51  0.49
20      id_1        NMHC  0.06   0.1  0.12  0.13  0.15  0.12  0.11  0.11  0.14
21      id_1          NO   0.5   0.7   1.5   1.9   1.8   1.7   1.8   1.8   1.8
22      id_1         NO2   5.5   9.4    13    11    10   9.5    10    10    11
23      id_1         NOx     6    10    14    12    12    11    12    12    13
24      id_1          O3    41    34    30    36    38    41    42    42    41
25      id_1        PM10    77    94   116   130   161   177   178   161   150
26      id_1       PM2.5    46    47    57    78    84    76    59    61    61
27      id_1    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
28      id_1          RH    62    60    56    51    48    44    45    45    47
29      id_1         SO2   5.6     6   6.8   7.1   6.4   5.8   5.8   5.9   5.7
...      ...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
4289  id_238         NOx    23    20    17    18    16    11    11   9.7   8.4
4290  id_238          O3    26    24    22    19    20    28    29    33    34
4291  id_238        PM10    70    71    53    45    42    33    33    32    48
4292  id_238       PM2.5    29    27    23    26    24    29    35    35    26
4293  id_238    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
4294  id_238          RH    54    60    67    70    73    73    74    75    75
4295  id_238         SO2   3.5   3.2   2.7   2.8   2.7   2.6   2.2   2.1   1.9
4296  id_238         THC     2     2   1.9     2     2   1.9     2   1.9   1.9
4297  id_238       WD_HR    56    83   116   128   103   115   119   114   101
4298  id_238  WIND_DIREC    63    99   110   141   117   114   127   121    98
4299  id_238  WIND_SPEED   1.1     1   1.8   1.3   1.9   1.9   1.7   2.9   1.8
4300  id_238       WS_HR   0.8   0.8   1.2   1.1   1.3   2.2   1.6   2.1   1.8
4301  id_239    AMB_TEMP    11    11    11    11    11    11    11    13    17
4302  id_239         CH4   1.7   1.7   1.8   1.7   1.7   1.7   1.8   1.7   1.8
4303  id_239          CO  0.32   0.3  0.31  0.24  0.21   0.3  0.97  0.64  1.09
4304  id_239        NMHC  0.08  0.06  0.07  0.05  0.04  0.09  0.35  0.24  0.67
4305  id_239          NO   1.5   1.1     1     1   1.5   2.2    23    12    19
4306  id_239         NO2   5.2   4.9   4.7     4   3.8   6.9    17    14    34
4307  id_239         NOx   6.7     6   5.8     5   5.3   9.1    40    26    53
4308  id_239          O3    13    16    22    17    14    12   4.5    11    17
4309  id_239        PM10    14    13    26    27    25     5     0     0    26
4310  id_239       PM2.5    12     8     7    11    11     3     0     0     0
4311  id_239    RAINFALL    NR    NR    NR    NR    NR    NR    NR    NR    NR
4312  id_239          RH    85    86    84    83    80    77    77    65    50
4313  id_239         SO2   1.1   1.3   1.4   1.3   1.1   1.4   2.7   2.7   8.2
4314  id_239         THC   1.8   1.8   1.8   1.8   1.7   1.8   2.1     2   2.5
4315  id_239       WD_HR   105   105   110    99   101   104    82    59   256
4316  id_239  WIND_DIREC   108   107   103    89    85   104    82   303   268
4317  id_239  WIND_SPEED   1.4   1.7   1.9   1.7   1.6   1.4   0.6   0.8   1.2
4318  id_239       WS_HR   1.4   1.7   1.6   1.8   1.8   1.6   0.6   0.5   0.5

[4319 rows x 11 columns]

In [29]:
pm2_5_test = testdata[testdata['AMB_TEMP']=='PM2.5'].iloc[:,2:]

In [31]:
x_test = np.array(pm2_5_test, float)
x_test

array([[27., 13., 24., ..., 29., 27., 28.],
       [46., 47., 57., ..., 59., 61., 61.],
       [10., 10., 25., ..., 36., 25., 22.],
       ...,
       [16., 25., 12., ..., 11.,  3.,  0.],
       [29., 27., 23., ..., 35., 35., 26.],
       [12.,  8.,  7., ...,  0.,  0.,  0.]])

In [32]:
# adding bias = 0
x_test_b = np.concatenate((np.ones((x_test.shape[0],1)),x_test),axis=1)

In [33]:
# predicting result
y_star = np.dot(x_test_b, weights)

In [34]:
y_star

array([ 27.41440924,  61.55574843,  20.4980879 ,  29.534512  ,
        10.79764676,  36.20722448,  39.71643873,  16.57174599,
        48.23626866,  33.98383059,  39.25397608,  58.4832285 ,
        37.23346974,  41.66913818,  27.55245239,  13.18884588,
        52.30030581,  23.63327146,  19.76623547,  20.51351383,
        15.66271563,  28.49276635,  38.03473423,  11.0807695 ,
        58.24255325,  44.53166848,  28.87675413,   9.80658048,
        29.69979803,  36.3508985 ,  19.43428986,  12.71482776,
        17.01176121,   8.62672283,  18.82223583,  38.66456477,
        20.08404389,  28.39277523,   6.94421262,  59.6890592 ,
        46.63325543,  17.28590255,  49.70849742,  18.98558787,
        44.15952936,  51.19901953,  61.64641674,  40.29587749,
        51.04031554,  42.08148093,  30.75654682,  25.437231  ,
        41.07788212,  26.36300133,  38.24279478,  39.90050018,
        25.70022586,  22.49550167,  37.45517401,  31.50167434,
        15.99340048,  23.13493177,  31.72291016,  55.05231391,
        49.79836207,  27.16914055,  41.80390054,  53.97691193,
        28.60290617,  39.58703354,  64.4100237 ,  53.21383763,
        44.59847861,  11.81686644,  13.28964339,  37.13647626,
        60.84703338,   3.7670425 ,  45.37959069,  41.11126257,
         8.83595972,  22.68053309,   8.15937808,  34.03007938,
        11.67533679,   5.75955154,  16.8761208 ,  12.03441343,
        13.36106062,  28.14532539,  30.62716061,  11.83503697,
        14.13207802,   8.39465645,  36.41782132,  16.17879296,
        16.2858257 ,   9.21372872,  11.67141566,   4.63456378,
        13.60862364,  18.48004167,  11.82112896,   6.07741292,
        14.7717746 ,  37.09938182,  27.4201087 ,   8.53079128,
        16.83555134,  17.0098858 ,  14.6874761 ,  18.12590899,
        13.88207211,  28.58420276,  23.14269349,  15.52077706,
        10.08343758,  44.56442732,  30.35990299,   2.10280046,
         2.92780476,  11.87210894,  16.39285733,  15.97082616,
         7.16371985,  27.2937623 ,  22.34012301,  13.73250178,
        20.50835714,  18.09571134,   4.66558915,  36.41192381,
        14.86600473,  27.4657649 ,  24.30029346,  21.97534938,
        10.8246142 ,  20.33378188,  77.23329153,  63.59368987,
        28.09053731,  18.15203336,  25.7172354 ,   8.85800546,
        12.31174116,  10.74981266,  22.28821988,   8.21716779,
        14.13614608,  17.60373762,  51.43021594,  21.67738383,
        24.63500955,  16.28079873,  14.92007408,  27.58824554,
        21.89752327,  34.45578101,   3.85933685,  20.42881368,
        44.05803685,  19.49914964,  55.62945218,  20.1244669 ,
        37.64356117,  25.48674646,  21.80504781,   2.10678562,
        66.67228544,  18.20524714,  18.40131747,  68.63538594,
        21.5288939 ,   3.35411768,  23.91706879,   3.19329103,
         7.33624164,  19.80236363,  21.02804768,  21.30165528,
        43.1004092 ,  27.72682244,  29.34499352,  12.92679352,
         9.49479103,  41.79173637,  37.56672471,  33.46522294,
        16.61187483,  22.27474769,  15.6460957 ,  15.43455986,
        33.50957888,  78.29428314,  29.69717969,  12.38996807,
        61.02890909,  16.30394266,  19.90082462,  24.05392724,
       124.91452644,  27.26684122,  58.66426887,   5.93116116,
        62.32534859,  36.08415864,  18.20735772,  15.24122963,
        63.81259842,  14.77438188,  30.38325769,  71.9105179 ,
        20.90171648, 117.49496727,  40.12753767,  82.30473274,
        92.80196405,  70.52028242,  29.61421077,  20.09478345,
        31.50253082,  54.62262258,  29.16276099,  40.04267752,
        44.66445636,   9.00644166,   4.90636098,  69.56826516,
        28.62108841,   2.3987995 ,  39.50858497,  15.63865831,
        22.31075738,   9.31801945,  12.25546423,  22.44360814,
        13.28596784,   0.69995897,  22.20097514,   1.88898093])

In [35]:
# put the predicted results to the output file
y_pre = pd.read_csv('sampleSubmission.csv')

In [36]:
y_pre.value = y_star
y_pre

         id       value
0      id_0   27.414409
1      id_1   61.555748
2      id_2   20.498088
3      id_3   29.534512
4      id_4   10.797647
5      id_5   36.207224
6      id_6   39.716439
7      id_7   16.571746
8      id_8   48.236269
9      id_9   33.983831
10    id_10   39.253976
11    id_11   58.483229
12    id_12   37.233470
13    id_13   41.669138
14    id_14   27.552452
15    id_15   13.188846
16    id_16   52.300306
17    id_17   23.633271
18    id_18   19.766235
19    id_19   20.513514
20    id_20   15.662716
21    id_21   28.492766
22    id_22   38.034734
23    id_23   11.080770
24    id_24   58.242553
25    id_25   44.531668
26    id_26   28.876754
27    id_27    9.806580
28    id_28   29.699798
29    id_29   36.350898
..      ...         ...
210  id_210   30.383258
211  id_211   71.910518
212  id_212   20.901716
213  id_213  117.494967
214  id_214   40.127538
215  id_215   82.304733
216  id_216   92.801964
217  id_217   70.520282
218  id_218   29.614211
219  id_219   20.094783
220  id_220   31.502531
221  id_221   54.622623
222  id_222   29.162761
223  id_223   40.042678
224  id_224   44.664456
225  id_225    9.006442
226  id_226    4.906361
227  id_227   69.568265
228  id_228   28.621088
229  id_229    2.398800
230  id_230   39.508585
231  id_231   15.638658
232  id_232   22.310757
233  id_233    9.318019
234  id_234   12.255464
235  id_235   22.443608
236  id_236   13.285968
237  id_237    0.699959
238  id_238   22.200975
239  id_239    1.888981

[240 rows x 2 columns]

In [37]:
#y_pre.to_csv('submission.csv')